---
title: "Analisis Regresi: Perbankan Syariah"
author: "David Syam Budi"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(readr)
library(dplyr)
```

```{r}
# Unduh data sebagai teks mentah dari GitHub (raw link)
url <- "https://raw.githubusercontent.com/davidsyambudi/Latihan-Kuantitatif/6301b4aba6f6d62e0dea96ae6e0ecaa3089a3b79/9b_data_perbankan_syariah.csv"
raw <- read_lines(url)

# Gabungkan kembali baris-baris menjadi satu teks utuh
csv_text <- paste(raw, collapse = "\n")

# Baca data dengan pemisah titik koma dan desimal koma
data <- read_delim(
  file = csv_text,
  delim = ";",
  locale = locale(decimal_mark = ","),
  col_types = cols(
    Periode = col_character(),
    ROA = col_double(),
    NPL = col_double(),
    SWBI = col_double(),
    IPI = col_double(),
    LDR = col_double()
  )
)

# Bersihkan data dari NA jika ada
data <- na.omit(data)

# Tinjau struktur data
glimpse(data)

```

```{r}
# Model regresi
model <- lm(LDR ~ ROA + NPL + SWBI + IPI, data = data)

# Tampilkan hasil regresi
summary(model)

```

```{r}
# Tambahkan hasil prediksi
data <- data %>% mutate(Prediksi = predict(model))

# Plot
plot(data$LDR, data$Prediksi,
     main = "LDR Aktual vs Prediksi",
     xlab = "LDR Aktual",
     ylab = "LDR Prediksi",
     col = "darkblue", pch = 19)
abline(a = 0, b = 1, col = "red", lwd = 2)

```

